FROM registry.cn-hangzhou.aliyuncs.com/pengdeeplearning/pytorch_cuda:torch20_vision015_cu117_cuda117_devel_ubuntu2204
ARG DEBIAN_FRONTEND=noninteractive

RUN apt -y install sudo \
    && pip config set global.index-url http://172.17.0.1:9997/root/pypi/+simple/ \
    && pip config set install.trusted-host 172.17.0.1 \
    && git config --global http.proxy http://172.17.0.1:9995 \
    && git config --global https.proxy http://172.17.0.1:9995 \
    && git config --global http.sslverify false \
    && echo "deb http://192.168.100.195:9998/ubuntu/ jammy main restricted universe multiverse" > /etc/apt/sources.list \
    && echo "deb http://192.168.100.195:9998/ubuntu/ jammy-updates main restricted universe multiverse" >> /etc/apt/sources.list \
    && echo "deb http://192.168.100.195:9998/ubuntu/ jammy-backports main restricted universe multiverse" >> /etc/apt/sources.list \
    && echo "deb http://192.168.100.195:9998/ubuntu/ jammy-security main restricted universe multiverse" >> /etc/apt/sources.list 
